#1.Importar y cargar el modelo preentrenado GPT de la librería transformers 

In [2]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.2 MB 4.2 MB/s 
     |████████████████████████████████| 596 kB 53.9 MB/s 
     |████████████████████████████████| 6.6 MB 39.8 MB/s 
     |████████████████████████████████| 86 kB 5.2 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [3]:
from transformers import TFOpenAIGPTLMHeadModel

model = TFOpenAIGPTLMHeadModel.from_pretrained("openai-gpt")


Downloading:   0%|          | 0.00/656 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/445M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFOpenAIGPTLMHeadModel.

All the layers of TFOpenAIGPTLMHeadModel were initialized from the model checkpoint at openai-gpt.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFOpenAIGPTLMHeadModel for predictions without further training.


#2.Se carga el tokenizador 

In [4]:
from transformers import OpenAIGPTTokenizer

tokenizer = OpenAIGPTTokenizer.from_pretrained("openai-gpt")

Downloading:   0%|          | 0.00/797k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/448k [00:00<?, ?B/s]

ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.


#3.Tokenización y codificación del mensaje de entrada 

In [5]:
prompt_text = "This royal throne of kings, this sceptred isle"
encoded_prompt = tokenizer.encode(prompt_text,
                                  add_special_tokens=False,
                                  return_tensors="tf")
encoded_prompt

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187]], dtype=int32)>

#4.Generación de texto

In [6]:
num_sequences = 5
length = 40

generated_sequences = model.generate(
    input_ids=encoded_prompt,
    do_sample=True,
    max_length=length + len(encoded_prompt[0]),
    temperature=1.0,
    top_k=0,
    top_p=0.9,
    repetition_penalty=1.0,
    num_return_sequences=num_sequences,
)

generated_sequences

<tf.Tensor: shape=(5, 49), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   240,   488,   500,   507,   240,   256, 27556,  7050,
          249,  2899,   240,   256,   655,   812,   580,  1272,  4187,
          240,   488,  1272,   989,   239,   256,   487,   626,   595,
          937,   481,  5860,  1820,   498,   481,  4640,  4187,   240,
          568,  2263,  3121,   551],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   544,   240,   500, 33931,   240,   670,  1203,   522,
         1667,  3099,  1218,  1122,   488,   616,   544,   481,   867,
          929,  2185,   498,  1385,   525,   589,   481, 12703,   500,
          616,  7339,   976,   699,   670,   240,   488,   674,   670,
         1667,  3099,  1218,  1663],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   509,  3194,  6432,   488,  1311,  6260,   815,   481,
         4582,  4814,   498

#5.Decodificación del texto generado e impresión de este 

In [7]:
for sequence in generated_sequences:
    text = tokenizer.decode(sequence, clean_up_tokenization_spaces=True)
    print(text)
    print("-" * 80)

this royal throne of kings, this sceptred isle, and in it,'kandrigi explained,'there will be many gods, and many people.'he did not say the actual power of the various gods, but simply laid out
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle is, in actuality, about three or four thousand years old and this is the two first lord of course that all the wizards in this kingdom really know about, and then about four thousand years ago
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle was truly vast and far greater than the distant lands of the west, the fabled country of issa's moon, where all the boys of issa's kin hailed from. in fact the great kingdom of
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle, of every class, and the noble titles which the west